image: docker:latest
services:
  - docker:dind

variables:
  di_name: 'officeaanglist'
  dd_name: 'officeaanglist'
  dd_route: '$d_route/officeaanglist:v0.3.2-puls'
  ddd_rout: 'homuras/officeaanglist:v0.3.2-puls'
  od_rout: "$d_route/office:7.1.1"
  #PIP_CACHE_DIR: .cache/pip

# cache:
#   paths:
#     - .cache/pip/
#     #- .cache/apt/
#   key: $CI_PROJECT_ID
#@include:
  #https://gitlab.homura.top:70/homura/officeaanglist.git
  #- remote: 'https://gitlab.homura.top:70/homura/officeaanglist/-/raw/confound/.gitlab-ci.yml'

stages:
  - build
  #- buildApp

build:
  stage: build
  script:
    - $confound_js.py > confound_js.py
    - docker-compose down
    - docker rmi $dd_route
    - docker build --build-arg od_rout=$od_rout -t $di_name .
    - docker login -u homura -p $lab_token $d_route
    - docker tag $di_name $dd_route
    - docker push $dd_route
    - docker-compose up -d
 
    # - docker login -u homuras -p $docker_token
    # - docker tag $di_name $ddd_rout
    # - docker push $ddd_rout
