image: docker:latest
services:
  - docker:dind

variables:
  di_name: 'officeaanglist'
  dd_name: 'officeaanglist'
  dd_route: '$d_route/officeaanglist:v0.1'
  ddd_rout: 'homuras/officeaanglist:v0.1'
  PIP_CACHE_DIR: ".cache/pip/"

cache:
  paths:
    - .cache/pip/
    - /var/lib/apt/lists/


stages:
  - build


build:
  stage: build
  script:
    #- /bin/sh init.sh
    - docker-compose down
    - docker build -t $di_name .
    - docker login -u homura -p $lab_token $d_route
    - docker tag $di_name $dd_route
    - docker push $dd_route
    - docker-compose up -d

    # - docker login -u homuras -p $docker_token
    # - docker tag $di_name $ddd_rout
    # - docker push $ddd_rout
