image: docker:latest
services:
  - docker:dind

variables:
  di_name: 'officeaanglist'
  dd_name: 'officeaanglist'
  dd_route: '$d_route/officeaanglist:v0.1'
  ddd_rout: 'homuras/officeaanglist:v0.1'
  PIP_CACHE_DIR: "$CI_PROJECT_ID/.cache/pip/"

cache:
  paths:
    - .cache/pip/
    - .cache/apt/
    key: "$CI_PROJECT_ID"


stages:
  - build


build:
  stage: build
  script:

    - docker-compose down
    - docker build --build-arg CI_PROJECT_ID=$CI_PROJECT_ID -t $di_name .
    - docker login -u homura -p $lab_token $d_route
    - docker tag $di_name $dd_route
    - docker push $dd_route
    - docker-compose up -d

    # - docker login -u homuras -p $docker_token
    # - docker tag $di_name $ddd_rout
    # - docker push $ddd_rout
