version: '3'
services:
  db:
    image: mariadb
    restart: always
    container_name: ${dd_name}-db
    environment:

      MYSQL_ROOT_PASSWORD: ${db_r}
      MYSQL_DATABASE: officeaanglist
      MYSQL_USER: officeaanglist
      MYSQL_PASSWORD: ${officedb_pw}
    volumes:
      - /home/homura/officeaanglist/db:/var/lib/mysql
    networks:
      - officeaanglist

  redis:
    image: redis
    container_name: ${dd_name}-redis
    restart: always
    command: redis-server /etc/redis/redis.conf --appendonly yes --requirepass 115099
    volumes:
      - /home/homura/officeaanglist/redis/redis.conf:/etc/redis/redis.conf
      - /home/homura/officeaanglist/redis/data:/data
    ports:
      - "6380:6379"
    networks:
      - officeaanglist
    logging:
      options:
        max-size: "100m"
        max-file: "2"

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   container_name: phpmyadminOffic
  #   ports:
  #     - "8051:80"
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: $db_r

  qbittorrent-nox:
    image: qbittorrentofficial/qbittorrent-nox:latest
    container_name: qbittorrent-nox
    tmpfs:
      - /tmp
    environment:
      - QBT_EULA=y
      - QBT_WEBUI_PORT=6901
    ports:
      - "6901:6901/tcp"
      - "6881:6881/tcp"
      - "6881:6881/udp"
    volumes:
      - "/home/homura/qbittorrent/config:/config"
      - "/home/homura/Download/qbittorrent:/downloads"
    networks:
      - officeaanglist

  onlyoffice:
    image: $dd_route
    #build: .
    container_name: ${dd_name}
    restart: always
    privileged: true
    #network_mode: "bridge"
    # dns:
      # - 192.168.0.37
    ports:
      - "8088:80"
      - "83:443"
    environment:
      - JWT_ENABLEN=false
      # - PUID=1000
      # - PGID=1000
      - TZ=Asia/Shanghai
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=officeaanglist
      - DB_USER=officeaanglist
      - DB_PWD=${officedb_pw}
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - REDIS_PASSWORD=115099
      - DOMAIN=${office_domain} #是否使用反向代理,如果使用反向代理,请填写https://****.com，并映射/ssl，证书文件应当是fullchain.pem和privkey.pem
      #- AListHost=     使用外部alist
      - AListdb_ty=mysql
      - AListdb_host=db
      - AListdb_port=3306
      - AListdb_us=officeaanglist
      - AListdb_pw=${officedb_pw}
      - AListdb_name=officeaanglist
      - qbit_host=qbittorrent-nox
      - aria2Csecret=QQ943384135   #aria2c的密钥建议更改！

    depends_on:
      - db
      - redis

    volumes:
      - /home/homura/officeaanglist/logs/:/var/log/
      - /home/homura/officeaanglist/app:/var/www/app:rw
      - /home/homura/AList:/AList
      - /home/homura/officeaanglist/lib:/var/lib/onlyoffice
      #- /volume1/docker/onlyoffice/db:/var/lib/postgresql
      - /home/homura/officeaanglist/conf.d:/etc/nginx/conf.d
      - /home/homura/ssl/homura.top:/ssl
      
    networks:
      - officeaanglist
      
networks:
  officeaanglist:
    name: officeaanglist