version: '3'
services:
  db:
    image: mariadb
    restart: always
    container_name: officeaanglist-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: officeaanglist
      MYSQL_USER: officeaanglist
      MYSQL_PASSWORD: 123456
    volumes:
      - /path/to/onlyoffice/db:/var/lib/mysql
    networks:
      - officeaanglist

  # phpmyadmin:
  #   image: phpmyadminOffic
  #   restart: always
  #   container_name: phpmyadminOffic
  #   ports:
  #     - "8051:80"
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: 159756

  qbittorrent-nox:
    image: qbittorrentofficial/qbittorrent-nox:latest
    container_name: qbittorrent-nox
    tmpfs:
      - /tmp
    environment:
      - QBT_EULA=y
      - QBT_WEBUI_PORT=6901
    ports:
      - "6901:6901/tcp"
      - "6881:6881/tcp"
      - "6881:6881/udp"
    volumes:
      - "/path/to/qbittorrent/config:/config"
      - "/path/to/Download/qbittorrent:/downloads"
    networks:
      - officeaanglist

  onlyoffice:
    image: homuras/officeaanglist:v0.1
    container_name: officeaanglist
    restart: always
    privileged: true
    #network_mode: "bridge"
    # dns:
      # - 192.168.0.37
    ports:
      - "80:80"
      - "443:443"
    environment:
      - JWT_ENABLEN=false
      - PUID=1000
      - PGID=1000
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=officeaanglist
      - DB_USER=officeaanglist
      - DB_PWD=123456
      #- REDIS_SERVER_HOST=127.0.0.1
      #- REDIS_SERVER_PORT=6379
      #- REDIS_PASSWORD=123456
      - DOMAIN=https://office.example.top:port
      - AListdb_ty=mysql
      - AListdb_host=db
      - AListdb_port=3306
      - AListdb_us=officeaanglist
      - AListdb_pw=123456
      - AListdb_name=officeaanglist
      - inReverProxy=false #是否使用反向代理,如果使用反向代理,请将其设置为true，并映射/ssl，证书文件应当是fullchain.pem和privkey.pem

    volumes:
      - /path/to/officeaanglist/logs:/var/log/onlyoffice
      - /path/to/officeaanglist/app:/var/www/app:rw
      - /path/to/officeaanglist/aria2:/var/www/app/aria2
      - /path/to/AList:/AList
      - /path/to/officeaanglist/lib:/var/lib/onlyoffice
      - /path/to/officeaanglist/db:/var/lib/postgresql
      - /path/to/officeaanglist/nginx-conf:/etc/nginx/conf.d
      #- /volume1/docker/onlyoffice/ssl:/ssl
    networks:
      - officeaanglist
      
networks:
  officeaanglist:
