#!/bin/bash

### BEGIN INIT INFO
# Provides:          alist
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: alist service
# Description:       alist service script
### END INIT INFO

# Change the following lines to match your application paths and options

APP_DIR=/var/www/app/AList
APP_EXEC=/var/www/app/AList/alist
APP_OPTIONS=server
LOG_FILE=/var/log/onlyoffice/app/alist.log
port=5244
check_port() {
    port=$1
    result=$(lsof -i :$port)
    if [ -n "$result" ]; then

        echo "$result"
        return 0  
    else
       
        return 1  
    fi
}
case "$1" in
    start)
        echo "Starting alist"
        cd $APP_DIR
        nohup $APP_EXEC $APP_OPTIONS 2>&1 | tee -a $LOG_FILE &
        echo "alist started"
        ;;
    stop)
        echo "Stopping alist"
        if check_port $port; then
            lsof -t -i :$port | xargs -r kill
        else
            echo "The process might not be running."
        fi
        ;;
    restart)
        echo "Restarting alist"
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if check_port $port; then
            echo "AList is running with PID $pid."
        else
            echo "AList is not running."
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
