#!/bin/bash

### BEGIN INIT INFO
# Provides:          alist
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: alist service
# Description:       alist service script
### END INIT INFO

# Change the following lines to match your application paths and options

APP_DIR=/var/www/app/AList
APP_EXEC=/var/www/app/AList/alist
APP_OPTIONS=server
LOG_FILE=/var/log/onlyoffice/app/alist.log
PID_FILE=/var/run/alist.pidls
case "$1" in
    start)
        echo "Starting alist"
        mkdir -p /var/log/onlyoffice/app 
        chmod -R g=u /var/log/onlyoffice/app 
        cd $APP_DIR
        nohup $APP_EXEC $APP_OPTIONS >> $LOG_FILE 2>&1 &
        echo $! > $PID_FILE  # Save the process ID to the PID file
        echo "alist started"
        ;;
    stop)
        echo "Stopping alist"
        if [ -f $PID_FILE ]; then
            kill $(cat $PID_FILE)  # Kill the process using the PID from the PID file
            rm $PID_FILE
            echo "alist stopped"
        else
            echo "PID file not found. The process might not be running."
        fi
        ;;
    restart)
        echo "Restarting alist"
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f $PID_FILE ]; then
            pid=$(cat $PID_FILE)
            if ps -p $pid > /dev/null; then
                echo "AList is running with PID $pid."
            else
                echo "AList is not running, but PID file exists."
            fi
        else
            echo "AList is not running."
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
