#!/bin/bash

### BEGIN INIT INFO
# Provides:          alist
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: alist service
# Description:       alist service script
### END INIT INFO

# Change the following lines to match your application paths and options

APP_DIR="/var/www/app/AList"
APP_EXEC="/var/www/app/AList/alist"
APP_OPTIONS="server"

case "$1" in
    start)
        echo "Starting alist"
        cd $APP_DIR
        nohup $APP_EXEC $APP_OPTIONS &
        ;;
    stop)
        echo "Stopping alist"
        killall -q $APP_EXEC
        ;;
    restart)
        echo "Restarting alist"
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
