#!/bin/bash

### BEGIN INIT INFO
# Provides:          aria2c
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Aria2c Download Manager
# Description:       Aria2c Download Manager service script
### END INIT INFO

# Change the following lines to match your application paths and options

ARIA2C_BIN="/usr/bin/aria2c"
ARIA2C_CONF="/var/www/app/aria2/aria2.conf"
ARIA2C_USER="root"

case "$1" in
    start)
        echo "Starting Aria2c Download Manager"
        nohup su -c "$ARIA2C_BIN --conf-path=$ARIA2C_CONF" $ARIA2C_USER &
        ;;
    stop)
        echo "Stopping Aria2c Download Manager"
        pgrep aria2c
        ;;
    restart)
        echo "Restarting Aria2c Download Manager"
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
