#!/bin/bash

### BEGIN INIT INFO
# Provides:          aria2c
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Aria2c Download Manager
# Description:       Aria2c Download Manager service script
### END INIT INFO

# Change the following lines to match your application paths and options

ARIA2C_BIN="/usr/bin/aria2c"
ARIA2C_CONF="/var/www/app/aria2/aria2.conf"
ARIA2C_USER="root"
LOG_FILE="/var/log/onlyoffice/app/aria2c.log"
PID_FILE="/var/run/aria2c.pid"

case "$1" in
    start)
        echo "Starting Aria2c Download Manager"
        nohup su -c "$ARIA2C_BIN --conf-path=$ARIA2C_CONF >> $LOG_FILE & echo \$!" $ARIA2C_USER > "$PID_FILE"
        echo "Aria2c Download Manager started"
        ;;
    stop)
        echo "Stopping Aria2c Download Manager"
        if [ -f "$PID_FILE" ]; then
            pid=$(cat "$PID_FILE")
            kill $pid
            rm "$PID_FILE"
            echo "Aria2c Download Manager stopped"
        else
            echo "PID file not found. The process might not be running."
        fi
        ;;
    restart)
        echo "Restarting Aria2c Download Manager"
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f "$PID_FILE" ]; then
            pid=$(cat "$PID_FILE")
            if ps -p $pid > /dev/null; then
                echo "Aria2c Download Manager is running with PID $pid."
            else
                echo "Aria2c Download Manager is not running, but PID file exists."
            fi
        else
            echo "Aria2c Download Manager is not running."
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
