#!/bin/bash

### BEGIN INIT INFO
# Provides:          viewer
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Your Viewer Service Description
# Description:       Start viewer service
### END INIT INFO

# Change the following line to match your Python3 path
PYTHON_BIN="/usr/bin/python3"
TB_USER='root'
LOG_FILE="/var/log/onlyoffice/app/viewer.log"
APP_DIR='/var/www/app/viewer'

PORTS_TO_KILL=(5000 5001)
check_port() {
    port=$1
    result=$(lsof -i :$port)
    if [ -n "$result" ]; then
     
        echo "$result"
        return 0  
    else
       
        return 1  
    fi
}

case "$1" in
    start)
        echo "Starting Viewer Service"
        cd $APP_DIR
        nohup $PYTHON_BIN viewer.py 2>&1 | tee -a $LOG_FILE &
        ;;
    stop)
        echo "Stopping Viewer Service"

        for port in "${PORTS_TO_KILL[@]}"; do
            if check_port $port; then
                lsof -t -i :$port | xargs -r kill
            fi
        done

        echo "Stopd Viewer Service"
        ;;
    restart)
        echo "Restarting Viewer Service"
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        for port in "${PORTS_TO_KILL[@]}"; do
            if check_port $port; then
                echo "Viewer Service is running on port $port"
            fi
        done
        exit 0
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
