#!/bin/bash

### BEGIN INIT INFO
# Provides:          viewer
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Your Viewer Service Description
# Description:       Start viewer service
### END INIT INFO

# Change the following line to match your Python3 path
PYTHON_BIN="/usr/bin/python3"
TB_USER='root'
LOG_FILE="/var/log/viewer.log"
PID_FILE="/var/run/viewer.pid"

case "$1" in
    start)
        echo "Starting Viewer Service"
        cd /var/www/app/viewer
        nohup $PYTHON_BIN viewer.py >> $LOG_FILE 2>&1 & echo $! > "$PID_FILE"
        ;;
    stop)
        echo "Stopping Viewer Service"
        if [ -f "$PID_FILE" ]; then
            pid=$(cat "$PID_FILE")
            kill $pid
            rm "$PID_FILE"
        else
            echo "PID file not found. The process might not be running."
        fi
        ;;
    restart)
        echo "Restarting Viewer Service"
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f "$PID_FILE" ]; then
            pid=$(cat "$PID_FILE")
            if ps -p $pid > /dev/null; then
                echo "Viewer Service is running with PID $pid."
            else
                echo "Viewer Service is not running, but PID file exists."
            fi
        else
            echo "Viewer Service is not running."
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
